module.exports = [
    "A day on Venus is longer than a year on Venus — it rotates slower than it orbits the Sun.",
    "Octopuses have three hearts and blue blood.",
    "Honey never spoils if it's stored properly — archaeologists have found edible honey in ancient Egyptian tombs.",
    "Bananas are botanically classified as berries. Strawberries, technically, are not.",
    "A group of flamingos is called a \"flamboyance.\"",
    "The Eiffel Tower can grow more than 6 inches taller in summer due to thermal expansion.",
    "Sharks existed before trees — they've been around for over 400 million years.",
    "Wombat poop is cube-shaped, which stops it from rolling away and marks their territory better.",
    "There are more possible chess games than atoms in the observable universe.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "The shortest war in history lasted about 38 minutes (the Anglo-Zanzibar War, 1896).",
    "Roblox launched in 2006 and originally let players build with physics-driven blocks called 'bricks.'",
    "A single cloud can weigh more than a million pounds.",
    "Cows have best friends and get stressed when separated from them.",
    "Butterflies taste with their feet.",
    "The unicorn is the national animal of Scotland.",
    "It rains diamonds on Jupiter and Saturn, according to atmospheric models.",
    "A bolt of lightning is roughly five times hotter than the surface of the Sun.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "Some cats can actually be allergic to humans, reacting to dead skin cells and hair.",
    "The Great Wall of China isn't actually visible from space with the naked eye.",
    "A 'jiffy' is a real unit of time — 1/100th of a second.",
    "Starfish don't have brains or blood.",
    "The first computer 'bug' was an actual moth stuck in a relay in 1947.",
    "Polar bears have black skin under their white fur to help absorb heat.",
    "The dot over a lowercase 'i' or 'j' is called a tittle.",
    "An ostrich's eye is bigger than its brain.",
    "The Mona Lisa has no eyebrows — it was fashionable in Renaissance Florence to shave them off.",
    "A single strand of spaghetti is called a 'spaghetto.'",
    "Slugs have four noses.",
    "Some turtles can breathe through their butts.",
    "A 'moment' was once an actual medieval unit of time — about 90 seconds.",
    "Elephants are one of the few animals that can recognize themselves in a mirror.",
    "The first oranges weren't orange — they were green, and the color-changing trait was bred in later.",
    "Venus is the only planet in our solar system that spins clockwise.",
    "The longest hiccuping spree on record lasted 68 years.",
    "A crocodile can't stick its tongue out.",
    "Wearing headphones for just an hour can increase the bacteria in your ear by 700 times.",
    "The inventor of the Frisbee, Walter Morrison, had his ashes molded into memorial discs after he died.",
    "Bubble wrap was originally invented as wallpaper.",
];
