module.exports = [
    ['have the ability to fly', 'have the ability to turn invisible'],
    ['always be 10 minutes late', 'always be 20 minutes early'],
    ['fight one horse-sized duck', 'fight 100 duck-sized horses'],
    ['never use social media again', 'never watch another movie or show again'],
    ['be able to talk to animals', 'be able to speak every human language'],
    ['have unlimited Robux but no friends to share it with', 'have unlimited friends but never earn Robux again'],
    ['live without music', 'live without air conditioning/heating'],
    ['be famous but broke', 'be rich but unknown'],
    ['only be able to whisper', 'only be able to shout'],
    ['have a rewind button for your life', 'have a pause button for your life'],
    ['always know when someone is lying to you', 'always get away with any lie you tell'],
    ['lose all your memories from the last year', 'never be able to make new memories again'],
    ['be the funniest person in the room', 'be the smartest person in the room'],
    ['have to sing everything you say', 'have to dance everywhere you go'],
    ['explore space', 'explore the deep ocean'],
    ['never be able to use a phone again', 'never be able to drive/travel again'],
    ['have super strength', 'have super speed'],
    ['live in a world with no internet', 'live in a world with no electricity'],
    ['always have to tell the truth', 'never be able to speak again'],
    ['be able to teleport anywhere', 'be able to read minds'],
];
